services:
  app:
    build: . # build folder
    container_name: backend-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-include * # Override the CMD command in Dockerfile
    ports:
      - 8080:8000
    volumes:
      - .:/app # .:/app - Override the COPY command in Dockerfile